packages:
  - 'packages/*'
  - 'packages/core/src/frontend'
  - 'playgrounds'

useNodeVersion: 22.17.0

catalog:
  'publint': '^0.3.12'
  'eslint': '^9.30.1'
  '@eslint/js': '^9.30.1'
  'eslint-plugin-svelte': '^3.10.1'
