packages:
  - packages/*
  - playgrounds/*

catalog:
  publint: ^0.3.16
  eslint: ^10.0.0
  '@eslint/js': ^10.0.0
  eslint-plugin-svelte: ^3.13.1
  '@playwright/test': ^1.57.0

useNodeVersion: 22.17.0
