packages:
  - packages/*
  - playgrounds/*

catalog:
  publint: ^0.3.15
  eslint: ^9.39.1
  '@eslint/js': ^9.39.1
  eslint-plugin-svelte: ^3.13.1
  '@playwright/test': ^1.57.0

useNodeVersion: 22.17.0
