packages:
  - packages/*
  - packages/core/src/frontend
  - playgrounds

catalog:
  publint: ^0.3.12
  eslint: ^9.31.0
  '@eslint/js': ^9.30.1
  eslint-plugin-svelte: ^3.11.0

useNodeVersion: 22.17.0
