packages:
  - packages/*
  - packages/core/src/frontend
  - playgrounds

catalog:
  publint: ^0.3.15
  eslint: ^9.38.0
  '@eslint/js': ^9.38.0
  eslint-plugin-svelte: ^3.12.5
  '@playwright/test': ^1.56.1

useNodeVersion: 22.17.0
